openapi: 3.0.0
info:
  title: BasiliskConnect API
  description: API specs for wifi access management solution.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: API serving server address
paths:
  /login:
    get:
      summary: Exchange user credentials to JWT.
      responses:
        "200": # status code
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
